
MOVE_INTERVAL_MS = 135

POINTS_PER_FOOD = 10

THEME_SHIFT_POINTS = 30

DESERT_SLOW_MULTIPLIER = 2

ICE_PRESS_STEPS = 3

STORM_GRACE_STEPS = 8

STORM_GUST_MIN = 1
STORM_GUST_MAX = 2

SPEED_BOOST_MULTIPLIER = 3
SPEED_BOOST_MS = 6000

STORM_BALL_VISIBLE_MIN_MS = 6_000
STORM_BALL_VISIBLE_MAX_MS = 10_000
STORM_BALL_HIDDEN_MIN_MS = 8_000
STORM_BALL_HIDDEN_MAX_MS = 14_000

PORTAL_COOLDOWN_STEPS = 15

PORTAL_CLEARANCE = 2

PORTAL_VISIBLE_MIN_MS = 10_000
PORTAL_VISIBLE_MAX_MS = 18_000
PORTAL_HIDDEN_MIN_MS = 5_000
PORTAL_HIDDEN_MAX_MS = 10_000

POINTS_COLOR_WRONG = 5

POISON_SPAWN_CHANCE = 0.28

INVULNERABILITY_TICKS = 10
OUTSIDE_COLLISION_STEPS_REQUIRED = 5
SHIELD_BREAK_GAME_OVER_LIMIT = 3
